/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.clsPasajero;
import classes.clsPasajeroAdulto;
import classes.clsTicket;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author mayko
 */
public class Ticket extends javax.swing.JFrame {

    
    LinkedList<clsTicket> listaTiquetes = new LinkedList<>();
    
    public Ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txSalida = new javax.swing.JTextField();
        txLlegada = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txFechaSalida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbHora = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbMinuto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbValor = new javax.swing.JComboBox<>();
        chbRetorno = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txNumeroAdultos = new javax.swing.JTextField();
        txNumeroNinos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txNombrePasajero = new javax.swing.JTextField();
        txApellidoPasajero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txNumeroDocumento = new javax.swing.JTextField();
        cbTipoDocumento = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txContacto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txCorreo = new javax.swing.JTextField();
        chbMenor = new javax.swing.JCheckBox();
        btAñadirPasajero = new javax.swing.JButton();
        btGenerarTiquete = new javax.swing.JButton();
        btImprimirTiquete = new javax.swing.JButton();

        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de Tiquetes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Viaje"));

        jLabel2.setText("Ciudad Salida");

        jLabel3.setText("Ciudad Llegada");

        jLabel4.setText("Fecha Salida");

        txFechaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFechaSalidaActionPerformed(evt);
            }
        });

        jLabel6.setText("(DD/MM/AAAA)");

        jLabel5.setText("Hora Salida");

        jLabel7.setText("Hora");

        cbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        jLabel8.setText("Minuto");

        cbMinuto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));
        cbMinuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMinutoActionPerformed(evt);
            }
        });

        jLabel9.setText("Valor Tiquete");

        cbValor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5000", "10000", "15000", "20000", "25000", "30000", "35000", "40000", "45000", "50000" }));

        chbRetorno.setText("Salida Y Regreso");
        chbRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbRetornoActionPerformed(evt);
            }
        });

        jLabel18.setText("#Adultos");

        jLabel19.setText("#Niños");

        txNumeroAdultos.setText("0");

        txNumeroNinos.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cbValor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbRetorno))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNumeroAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNumeroNinos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(txNumeroAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNumeroNinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(cbMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbRetorno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Pasajero"));

        jLabel10.setText("Nombre");

        jLabel11.setText("Apellidos");

        txNombrePasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNombrePasajeroActionPerformed(evt);
            }
        });

        jLabel12.setText("Tipo de Documento");

        jLabel13.setText("Numero ID");

        cbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI" }));

        jLabel14.setText("Genero");

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGeneroActionPerformed(evt);
            }
        });

        jLabel15.setText("Contacto");

        txContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txContactoActionPerformed(evt);
            }
        });

        jLabel17.setText("Correo");

        chbMenor.setText("Menor de edad");

        btAñadirPasajero.setText("Añadir");
        btAñadirPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAñadirPasajeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(18, 18, 18)
                            .addComponent(txCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(txNombrePasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(chbMenor)
                        .addGap(18, 18, 18)
                        .addComponent(btAñadirPasajero))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(18, 18, 18)
                            .addComponent(txContacto))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(txApellidoPasajero))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txNombrePasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txApellidoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbMenor)
                    .addComponent(btAñadirPasajero))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btGenerarTiquete.setBackground(new java.awt.Color(255, 204, 51));
        btGenerarTiquete.setText("Generar Nuevo Tiquete");
        btGenerarTiquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerarTiqueteActionPerformed(evt);
            }
        });

        btImprimirTiquete.setText("Imprimir Tiquete");
        btImprimirTiquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirTiqueteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btImprimirTiquete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btGenerarTiquete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btGenerarTiquete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btImprimirTiquete))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txFechaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFechaSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFechaSalidaActionPerformed

    private void chbRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbRetornoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbRetornoActionPerformed

    private void cbMinutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMinutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMinutoActionPerformed

    private void btGenerarTiqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerarTiqueteActionPerformed

        String nombre = txNombrePasajero.getText();
        String apellido = txApellidoPasajero.getText();
        String tipoDocumento = cbTipoDocumento.getSelectedItem().toString();
        String numeroDocumento = txNumeroDocumento.getText();
        String sexo = cbGenero.getSelectedItem().toString();
        boolean retorno = chbRetorno.isSelected();
        boolean menor = chbMenor.isSelected();
        
        
        String salida = txSalida.getText();
        String llegada = txLlegada.getText();
        String fechaSalida = txFechaSalida.getText();
        String horaSalida = cbHora.getSelectedItem().toString() + cbMinuto.getSelectedItem().toString();
        double valorTrayecto = Double.parseDouble(cbValor.getSelectedItem().toString());
        int numeroAdultos = Integer.parseInt(txNumeroAdultos.getText());
        int numeroninos = Integer.parseInt(txNumeroNinos.getText());
        
                
        
        if(!salida.equals("") && !llegada.equals("") && !fechaSalida.equals("") && !horaSalida.equals("") && valorTrayecto != 0){
            if(!nombre.equals("") && !apellido.equals("") && !tipoDocumento.equals("") && !numeroDocumento.equals("") && !sexo.equals("") ){
                if(menor){
                    clsPasajero pasajeroNino = new clsPasajero(nombre, apellido, tipoDocumento, numeroDocumento, sexo);
                    clsTicket ticket = new clsTicket(salida, llegada, fechaSalida, horaSalida, numeroAdultos, numeroninos, valorTrayecto, retorno, pasajeroNino);
                    listaTiquetes.add(ticket);
                    JOptionPane.showMessageDialog(this, "Se genero el tiquete exitosamente, Ingrese los otros pasajeros y luego de en Imprimir Tiquete");
                    limpiarFormularioPasajero();
                    //limpiarFormularioViaje();

                    
                    
                }
                else{
                    String contacto = txContacto.getText();
                    String correo = txCorreo.getText();
                    if(!contacto.equals("") && !correo.equals("")){
                        clsPasajeroAdulto pasajeroAdulto = new clsPasajeroAdulto(nombre, apellido, tipoDocumento, numeroDocumento, sexo, contacto, correo);
                        clsTicket ticket = new clsTicket(salida, llegada, fechaSalida, horaSalida, numeroAdultos, numeroninos, valorTrayecto, retorno, pasajeroAdulto);
                        listaTiquetes.add(ticket);
                        JOptionPane.showMessageDialog(this, "Se genero el tiquete exitosamente, Ingrese los demas pasajeros y luego de en Imprimir Tiquete");
                        limpiarFormularioPasajero();
                        //limpiarFormularioViaje();
                        
                        
                    }
                    else
                        JOptionPane.showMessageDialog(this, "Ingrese los datos de contacto del mayor de edad");
  
                }
                
            }
            else
                JOptionPane.showMessageDialog(this, "Ingrese todos los datos del viaje y del pasajero");
            
        }else{            
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos del viaje y del pasajero");
        }
        
    }//GEN-LAST:event_btGenerarTiqueteActionPerformed

    private void txContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txContactoActionPerformed

    private void cbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGeneroActionPerformed

    private void txNombrePasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNombrePasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNombrePasajeroActionPerformed

    private void btAñadirPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAñadirPasajeroActionPerformed
        
        String nombre = txNombrePasajero.getText();
        String apellido = txApellidoPasajero.getText();
        String tipoDocumento = cbTipoDocumento.getSelectedItem().toString();
        String numeroDocumento = txNumeroDocumento.getText();
        String sexo = cbGenero.getSelectedItem().toString();
        boolean retorno = chbRetorno.isSelected();
        boolean menor = chbMenor.isSelected();
        
        if(listaTiquetes.isEmpty())
            JOptionPane.showMessageDialog(this, "No ha generado ningun Tiquete. \n1- Llene el formulario completo \n2- \"Generar Nuevo Tiquete\"  \n3- Añada a los pasajeros restantes \n4- \"Imprimir Tiquete\"");
        else{
            if(!nombre.equals("") && !apellido.equals("") && !tipoDocumento.equals("") && !numeroDocumento.equals("") && !sexo.equals("") ){
                    if(menor){
                        clsPasajero pasajeroNino = new clsPasajero(nombre, apellido, tipoDocumento, numeroDocumento, sexo);


                        LinkedList<clsPasajero> aux = listaTiquetes.getLast().getListaObjetosPasajero();
                            aux.add(pasajeroNino);   

                            listaTiquetes.getLast().setListaObjetosPasajero(aux);
                            JOptionPane.showMessageDialog(this, "Se añadio al pasajero en el tiquete exitosamente.");
                            limpiarFormularioPasajero();

                    }
                    else{
                        String contacto = txContacto.getText();
                        String correo = txCorreo.getText();
                        if(!contacto.equals("") && !correo.equals("")){
                            clsPasajeroAdulto pasajeroAdulto = new clsPasajeroAdulto(nombre, apellido, tipoDocumento, numeroDocumento, sexo, contacto, correo);



                            LinkedList<clsPasajeroAdulto> aux = listaTiquetes.getLast().getListaObjetosPasajeroAdulto();
                            aux.add(pasajeroAdulto);

                            listaTiquetes.getLast().setListaObjetosPasajeroAdulto(aux);
                            JOptionPane.showMessageDialog(this, "Se añadio al pasajero en el tiquete exitosamente.");
                            limpiarFormularioPasajero();


                        }
                        else
                            JOptionPane.showMessageDialog(this, "Ingrese los datos de contacto del mayor de edad");

                    }  
                }
            
                else
                    JOptionPane.showMessageDialog(this, "Ingrese todos los datos del viaje y del pasajero");
    }

        
    }//GEN-LAST:event_btAñadirPasajeroActionPerformed

    private void btImprimirTiqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirTiqueteActionPerformed
        try{
            System.out.print(imprimirTicket(listaTiquetes.getLast()));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "No ha generado ningun Tiquete, genere uno y luego añada a los pasajeros");
        }
    }//GEN-LAST:event_btImprimirTiqueteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }
    
     public String imprimirTicket(clsTicket ticket){
         
         System.out.println("- - - - - - - - TIQUETE DE VIAJE - - - - - - ");
        double valorTotal = ticket.getValor()*(ticket.getCantidadAdultos()+ticket.getCantidadNiños());
        if(ticket.isRetorno())
            valorTotal = valorTotal *2;
        String informacionTicket = "- - - - - - - - - - -  - - - - - - - - - - -" + "\n" + "Lugar de salida: " + ticket.getSalida() + "       " + " Lugar de destino: " + ticket.getLlegada() + "\n" + "Fecha de salida: " + ticket.getFechaSalida()  + "    Hora salida: " + ticket.getHora() + "\n" + "Pasajeros adultos: " + ticket.getCantidadAdultos() +  " Pasajeros niños: "+ ticket.getCantidadNiños() + "\n" + "Ida y Vuelta: " + ticket.isRetorno() + "\n" + "Valor Unitario: " + ticket.getValor()  + "Valor Total: " + valorTotal +  "\n- - - - - - - - - - -  - - - - - - - - - - -" ;
        String informacionPasajeros = "";

        LinkedList<clsPasajero> listaObjetosPasajero =  ticket.getListaObjetosPasajero();
       
        for(clsPasajero pasajeroNino : listaObjetosPasajero){
            informacionPasajeros = "\n- - - - - - - - - - -  - - - - - - - - - - - \n" + informacionPasajeros + "\n" + "Pasajero: " + pasajeroNino.getNombre() + " " + pasajeroNino.getApellido() + "\nTipo de documento: " + pasajeroNino.getTipoDocumento() + "   " + " Numero de documento: " + pasajeroNino.getNumeroDocumento() +   "\nGenero: " + pasajeroNino.getSexo() + "\n- - - - - - - - - - -  - - - - - - - - - - - \n";
        }
        
        LinkedList<clsPasajeroAdulto> listaObjetosPasajeroAdulto =  ticket.getListaObjetosPasajeroAdulto();
        
        for(clsPasajeroAdulto pasajeroAdulto : listaObjetosPasajeroAdulto){
            informacionPasajeros ="\n- - - - - - - - - - -  - - - - - - - - - - - \n" + informacionPasajeros + "\n" + "Pasajero: " + pasajeroAdulto.getNombre() + " " + pasajeroAdulto.getApellido() + "\nTipo de documento: " + pasajeroAdulto.getTipoDocumento() + "   " + " Numero de documento: " + pasajeroAdulto.getNumeroDocumento() + "\nGenero: " + pasajeroAdulto.getSexo() + "\nCorreo Electrónico: " + pasajeroAdulto.getCorreoElectronico()+ "\nCelular:  " + pasajeroAdulto.getContacto() + "\n- - - - - - - - - - -  - - - - - - - - - - - \n";
        }
        
        
        
        return informacionTicket + informacionPasajeros;
    }
     
     public void limpiarFormularioPasajero(){
         txNombrePasajero.setText("");
         txApellidoPasajero.setText("");
         txCorreo.setText("");
         txContacto.setText("");
         txNumeroDocumento.setText("");
     }
     
     public void limpiarFormularioViaje(){
         txSalida.setText("");
         txLlegada.setText("");
         txFechaSalida.setText("");
         txNumeroAdultos.setText("0");
         txNumeroNinos.setText("0");
         txFechaSalida.setText("0");
         
         
     }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAñadirPasajero;
    private javax.swing.JButton btGenerarTiquete;
    private javax.swing.JButton btImprimirTiquete;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JComboBox<String> cbHora;
    private javax.swing.JComboBox<String> cbMinuto;
    private javax.swing.JComboBox<String> cbTipoDocumento;
    private javax.swing.JComboBox<String> cbValor;
    private javax.swing.JCheckBox chbMenor;
    private javax.swing.JCheckBox chbRetorno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txApellidoPasajero;
    private javax.swing.JTextField txContacto;
    private javax.swing.JTextField txCorreo;
    private javax.swing.JTextField txFechaSalida;
    private javax.swing.JTextField txLlegada;
    private javax.swing.JTextField txNombrePasajero;
    private javax.swing.JTextField txNumeroAdultos;
    private javax.swing.JTextField txNumeroDocumento;
    private javax.swing.JTextField txNumeroNinos;
    private javax.swing.JTextField txSalida;
    // End of variables declaration//GEN-END:variables
}
